#!/bin/sh -e

mkdir -p ./docs
rm -rf ./docs/src
rm -rf ./docs/build
git clone https://github.com/martenframework/marten ./docs/src

cd ./docs/src
shards install
crystal docs --output=docs/static/api/dev
for version in 0.1.5 0.2.3
do
  git checkout v$version
  doc_version=$(echo $version | rev | cut -c3- | rev)
  crystal docs --output=docs/static/api/$doc_version --project-version=$doc_version
done
git checkout main

cd ./docs
npm i
npm run -- docusaurus build --out-dir=../../build
