name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  js_qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install Node.js dependencies
      run: npm ci
    - name: Run QA checks
      run: |
        make lint_js

  crystal_qa:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.2.2
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install
      - name: Run QA checks
        run: make qa_crystal

  crystal_tests:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.2.2
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install
      - name: Run tests suite
        run: make tests_crystal
