name: Deploy

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: ${{ secrets.DO_APP_NAME }}
          token: ${{ secrets.DO_ACCESS_TOKEN }}
