name: QA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  crystal:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.13.0
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          apt-get update
          apt-get -yqq install cmake build-essential
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Run QA checks
        run: make qa_crystal
  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install JS dependencies
        run: npm install
      - name: Run QA checks
        run: make qa_js
